name: "jaffle_shop"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  jaffle_shop:
    materialized: table
    staging:
      materialized: view
    table_glue:
      materialized: table_glue

seeds: 
  jaffle_shop:
    column_overrides:
      boolean_type:
        +column_types:
          boolean_example: boolean
      datetime_type:
        +column_types:
          date_example: date
          time_example: time
          time_p_example: time(6)
          time_tz_example: time with time zone
          timestamp_example: timestamp
          timestamp_p_example: timestamp(6)
          timestamp_tz_example: timestamp with time zone
          timestamp_p_tz_example: timestamp(6) with time zone
          interval_ym_example: interval year to month
          interval_ds_example: interval day to second
      number_type:
        +column_types:
          integer_example: integer
          tinyint_example: tinyint
          smallint_example: smallint
          bigint_example: bigint
          real_example: real
          double_example: double
          decimal_example: decimal
          decimal_p_example: decimal(3, 2)
      string_type:
        +column_types:
          varchar_example: varchar
          varchar_n_example: varchar(10)
          char_example: char
          char_n_example: char(10)
          varbinary_example: varbinary
          json_example: json

